version: "3"
services:
  communication-gateway:
    container_name: communication-gateway
    image: communication-gateway:latest
    ports:
    - "8000:8000"
    restart: always

  communication-consumer:
    container_name: communication-consumer
    image: communication-consumer:latest
    ports:
    - "8081:8081"
    restart: always

  communication-auth:
    container_name: communication-auth
    image: communication-auth:latest
    ports:
    - "8083:8083"
    restart: always

  communication-provider:
    container_name: communication-provider
    image: communication-provider:latest
    ports:
    - "8082:8082"
    restart: always
  docker run -d -p 8080:8000  --rm communication-gateway
